ifdef __BARE_METAL__

PREFIX := arm-none-eabi-
DEFINES += -D__BARE_METAL__
CPP := $(PREFIX)g++
CC := $(PREFIX)gcc
AS := $(PREFIX)as
AR := $(PREFIX)ar
LD := $(PREFIX)ld

endif


RM := rm -rf

CPP ?= $(PREFIX)g++
CC ?= $(PREFIX)gcc
AS := $(PREFIX)as
AR := $(PREFIX)ar
LD ?= $(PREFIX)g++ #ld


INCLUDES := -I$(TOPDIR)/utils -I$(TOPDIR)/bsp -I$(TOPDIR)/external_devices

CPPFLAGS += -std=c++0x -O0 -Wall -fmessage-length=0
CFLAGS += -std=c99 -O0 -Wall -fmessage-length=0

%.o: %.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	$(CPP) $(CPPFLAGS) $(INCLUDES) $(DEFINES) -o "$@" -c "$<"
	@echo 'Finished building: $<'
	@echo ' '

%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -o "$@" -c "$<"
	@echo 'Finished building: $<'
	@echo ' '

%.o: %.S
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	$(AS) $(AOPTS) $(INCLUDES)  -o "$@" -c "$<"
	@echo 'Finished building: $<'
	@echo ' '
